<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RelatorioToggl.Api</RootNamespace>
    <AssemblyName>TogglReport.Api</AssemblyName>
    <InvariantGlobalization>false</InvariantGlobalization>
    <NeutralLanguage>pt-BR</NeutralLanguage>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TogglReport.Nucleo\TogglReport.Nucleo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

</Project>
